apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-webapp
  template:
    metadata:
      labels:
        app: my-webapp
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
      - name: webapp
        image: __IMAGE_URL__
        ports:
        - containerPort: 5000